name: Deploy to BisectHosting
on:
    push:
        branches: [master]
    workflow_dispatch:
        inputs:
          sync:
            description: "File synchronization"
            required: true
            default: "delta"
jobs:
    deploy_master:
      name: "master branch"
      if: ${{ github.ref == 'refs/heads/master' }}
      runs-on: ubuntu-latest
      steps:
      - name: Checkout to branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set discord token"
        run: echo "TOKEN=${{ secrets.env_token }}" >> env
      - name: "Deploying files"
        uses: milanmk/actions-file-deployer@master
        with:
            remote-protocol: "sftp"
            remote-host: ${{ secrets.ftp_host }}
            remote-user: ${{ secrets.ftp_username }}
            remote-password: ${{ secrets.ftp_password }}
            port: ${{ secrets.ftp_port }}
            local_path: './*'
            remote_path: '/home/container/'
